from typing import List, Optional
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """
    In-memory dialogue message for conversation context.
    """
    role: str = Field(..., description="Message author role: 'user' or 'model'")
    content: str = Field(..., min_length=1, max_length=4000, description="Message text content")


class AILearnRequest(BaseModel):
    """
    Request model for Socratic AI learning tutoring.
    """
    subject_slug: str = Field(..., min_length=1, max_length=100, description="Slug of the selected curriculum subject")
    concept_slug: str = Field(..., min_length=1, max_length=100, description="Slug of the selected concept unit")
    message: str = Field(..., min_length=1, max_length=4000, description="Student question or reflection")
    history: Optional[List[ChatMessage]] = Field(default=None, description="Recent in-memory conversation history")


class AILearnResponse(BaseModel):
    """
    Response model containing the generated AI tutoring response.
    """
    message: str = Field(..., description="Socratic tutoring explanation generated by AI")
    subject: str = Field(..., description="Subject name")
    concept: str = Field(..., description="Concept name")
    provider: str = Field(default="gemini", description="AI Provider identifier")
    model: str = Field(..., description="Model identifier used for generation")
